SF2Field(char20, sampleName)
SF2Field(dword, start)
SF2Field(dword, end)
SF2Field(dword, startLoop)
SF2Field(dword, endLoop)
SF2Field(dword, sampleRate)
SF2Field(byte, originalPitch)
SF2Field(char, pitchCorrection)
SF2Field(word, sampleLink)
SF2Field(word, sampleType)

